services:
  app:
    image: ${DOCKER_USERNAME}/${DOCKER_REPO}:latest
    ports:
      - "8080:8080"  # 호스트의 8080 포트를 컨테이너의 8080 포트와 매핑
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=dev # dev 배포
      - TZ=Asia/Seoul
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    command: java -Duser.timezone=Asia/Seoul -Dspring.profiles.active=${SPRING_PROFILES_ACTIVE} -jar app.jar
    depends_on:
      mysql: # 이 서비스가 mysql이 먼저 실행된 후 시작되도록
        condition: service_healthy # mysql 헬스 체크 추가(mysql 컨테이너 시작이 아니라 완전히 준비됐는지 여부 확인 용)

    networks:
      - cesco-network  # mysql과 같은 네트워크를 공유

  mysql:
    image: mysql:8.0  # 공식 MySQL 8.0 이미지를 사용
    ports:
      - "3306:3306"  # 호스트와 컨테이너의 MySQL 포트를 매핑
    environment:
      - MYSQL_DATABASE=setbangsari  # 초기 생성될 데이터베이스 이름
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}  # 루트 계정의 비밀번호
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-authentication-plugin=mysql_native_password
      - --init-connect=SET NAMES utf8mb4
      - --default-time-zone=+09:00
    healthcheck: # mysql 헬스 체크 추가
      test: [ "CMD", "mysqladmin", "ping", "-h",
              "localhost", "-uroot", "-p${MYSQL_ROOT_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s  # 초기 실행 유예 시간, 이 동안 실패해도 retries 차감 안 됨
    volumes:
      - mysql-data:/var/lib/mysql
        # MySQL의 데이터 파일을 호스트에 볼륨으로 영구 저장
      # 컨테이너가 삭제돼도 DB 내용은 유지됨
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - cesco-network  # Spring과 같은 네트워크 상에 있어서 mysql이라는 호스트 이름으로 접근 가능

networks:
  cesco-network:
    driver: bridge  # Docker 기본 브리지 네트워크를 사용

volumes:
  mysql-data:  # 위에서 정의한 MySQL 데이터를 저장할 볼륨